name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev

      - name: Run linter
        run: make lint

      - name: Run tests
        run: uv run pytest tests/ --cov=gendiff --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=GrayFox-source_python-project-50
            -Dsonar.organization=grayfox-source
            -Dsonar.python.coverage.reportPaths=coverage.xml